### ISSUE TITLE
Fix image meta og and twitter tags on blog (then website)

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#76]
## Current Behavior
I updated the `meta property="og:image"` URL to a valid URL. That way when the link is posted on another site, an image preview should appear. But, it's not working.

![image](https://user-images.githubusercontent.com/1372946/56071790-8232ba80-5d45-11e9-92ca-5bb4b901ae7e.png)

![link](https://user-images.githubusercontent.com/1372946/56071772-54e60c80-5d45-11e9-88b4-81b9fb47a746.gif)

## Expected Behavior
Image from `og:image` should appear in preview.

## Follow-on: ember-website

- [ ] ember-website has an [image URL](https://github.com/ember-learn/ember-website/blob/02fafea3f182d1e7d8d6769bd7655ff5fb4b5a07/app/index.html#L12) for `og:image` where the URL is no longer valid. 

## Follow-on: Twitter

- [ ] Once this is solved, we should fix this for Twitter link previews as well: 
![image](https://user-images.githubusercontent.com/1372946/56071812-b4dcb300-5d45-11e9-9dcf-3114ad8eaab4.png)

**Comment by amyrlam** [comment]
Now I'm seeing one of the images from a past iteration, maybe it takes some time. Waiting...

**Comment by amyrlam** [comment]
Thanks to @ijlee2's help on Discord, I got this fixed on open graph. See ([Facebook](https://developers.facebook.com/tools/debug/sharing/) or [LinkedIn](https://www.linkedin.com/post-inspector/) "check meta tags" links for reference.

![image](https://user-images.githubusercontent.com/1372946/56073369-705a1300-5d57-11e9-834f-d84ffda8ec6b.png)

Twitter is also an improvement!
![image](https://user-images.githubusercontent.com/1372946/56073378-7fd95c00-5d57-11e9-8462-f0ad262eb197.png)

- [ ] The `og:description` description is quite long, we probably want something shorter that will fit on social shares, see https://github.com/ember-learn/ember-blog/blob/master/source/layout.erb#L14

- [ ] The images have a strange URL (several numbers appended to end) https://github.com/ember-learn/ember-website/tree/master/public/images/brand and it seems like these could be modified by designer at any time. see https://github.com/ember-learn/ember-blog/blob/master/source/layout.erb#L13

**Comment by ijlee2** [comment]
Looks great!

**Comment by amyrlam** [comment]
Spoke to @mansona. Had made this change on ember-blog: https://github.com/ember-learn/ember-blog/blob/7865c15d55702c1f652442fd89ed797c2e221dbb/source/layout.erb#L13-L19

Should exclude image files from fingerprinting in the Ember CLI build, and then make the change on ember-learn/ember-website: https://github.com/ember-learn/ember-website/blob/master/app/index.html#L12-L17

**Comment by chrisrng** [comment]
The image actually seems to load (albeit the image is just the svg logo)
see: https://www.linkedin.com/post-inspector/inspect/emberjs.com%2Fblog

**Comment by amyrlam** [comment]
It seems like this can be closed, working for now, since the website is in the process of being updated.
